version: 2.1

jobs:
  linux-terminal:
    docker:
      - image: cimg/base:stable  # Basic Linux container
    steps:
      - checkout
      - run:
          name: Print Linux Info
          command: 
          !lscpu 
          !sudo apt update
          !sudo apt upgrade -y
          !curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          !echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          !sudo apt install playit
          !playit
          !playit secret-path

workflows:
  linux-terminal-workflow:
    jobs:
      - linux-terminal
