version: 2.1

jobs:
  linux-terminal:
    docker:
      - image: cimg/base:stable  # Basic Linux container
    steps:
      - checkout
      - run:
          name: Print Linux Info
          command: 
          lscpu

workflows:
  linux-terminal-workflow:
    jobs:
      - linux-terminal
